### ISSUE TITLE
Is the HTTP.request() method a async function?

### ISSUE THREAD

**Issue by daibor** [agiletortoise/drafts-script-reference#1]
Hi, I run the [HTTP.request() method](https://scripting.getdrafts.com/classes/http) successfully, but the `response.success` always return `0`.I think this method should return a Promise or receive a callback function to get the response.

**Comment by agiletortoise** [comment]
All Drafts library functions are synchronous. This is intentional because actions are not ongoing processes. They have a determinate execution path. It is possible to use async constructs, but the Script action steps must be marked for aync support and the burden is on the script writer to let Drafts know when the script is complete. See [Script object docs](https://scripting.getdrafts.com/classes/script).
